aws_region_dict = {
    "Ohio": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Illinois": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Indiana": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Iowa": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Kansas": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Michigan": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Minnesota": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Missouri": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Nebraska": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "North Dakota": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "South Dakota": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Wisconsin": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Arkansas": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Louisiana": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Oklahoma": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Texas": ("US East","us-east-2",["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]),
    "Alabama": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Kentucky": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Mississippi": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Tennessee":  ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Delaware": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "District of Columbia": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Florida": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Georgia": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Maryland": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "North Carolina": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "South Carolina": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "West Virginia": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "Virginia": ("US East","us-east-1",["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]),
    "California": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Arizona": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Colorado": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Idaho": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Montana": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Nevada": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "New": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Mexico": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Utah": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Wyoming": ("US West","us-west-1",["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]),
    "Alaska": ("US West","us-west-2",["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]),
    "Hawaii": ("US West","us-west-2",["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]),
    "Oregon": ("US West","us-west-2",["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]),
    "Washington": ("US West","us-west-2",["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]),
}