aws_region_dict = {
    "Ohio": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Illinois": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Indiana": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Iowa": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Kansas": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Michigan": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Minnesota": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Missouri": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Nebraska": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "North Dakota": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "South Dakota": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Wisconsin": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Arkansas": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Louisiana": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Oklahoma": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Texas": {"region_name":"US East","region_code":"us-east-2","base_urls":["rds.us-east-2.amazonaws.com, rds-fips.us-east-2.api.aws, rds.us-east-2.api.aws, rds-fips.us-east-2.amazonaws.com"]},
    "Alabama": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Kentucky": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Mississippi": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Tennessee":  {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Delaware": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "District of Columbia": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Florida": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Georgia": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Maryland": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "North Carolina": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "South Carolina": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "West Virginia": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "Virginia": {"region_name":"US East","region_code":"us-east-1","base_urls":["rds.us-east-1.amazonaws.com","rds-fips.us-east-1.api.aws","rds-fips.us-east-1.amazonaws.com","rds.us-east-1.api.aws"]},
    "California": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Arizona": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Colorado": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Idaho": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Montana": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Nevada": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "New": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Mexico": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Utah": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Wyoming": {"region_name":"US West","region_code":"us-west-1","base_urls":["rds.us-west-1.amazonaws.com","rds.us-west-1.api.aws","rds-fips.us-west-1.amazonaws.com","rds-fips.us-west-1.api.aws"]},
    "Alaska": {"region_name":"US West","region_code":"us-west-2","base_urls":["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]},
    "Hawaii": {"region_name":"US West","region_code":"us-west-2","base_urls":["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]},
    "Oregon": {"region_name":"US West","region_code":"us-west-2","base_urls":["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]},
    "Washington": {"region_name":"US West","region_code":"us-west-2","base_urls":["rds.us-west-2.amazonaws.com","rds-fips.us-west-2.amazonaws.com","rds.us-west-2.api.aws","rds-fips.us-west-2.api.aws"]},
}